version: '3.6'
services:
  exporter-github:
    build: .
    cap_drop:
      - ALL
    read_only: true
    environment:
      - NODE_ENV
      - HTTP_PORT
      - LOG_FORMAT
      - LOG_LEVEL
      - GITHUB_TOKEN
      - GITHUB_ORGANISATION
    ports:
    - "8080:8080"
    command: ["yarn", "start"]
    volumes:
      - .:/app
      - /tmp
    restart: always
  prometheus:
    image: prom/prometheus:latest
    ports:
    - "9090:9090"
    volumes:
    - ./.docker-compose/prometheus/etc/prometheus:/etc/prometheus
    depends_on:
    - exporter-github
