version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.0
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: 'prometheus-exporter-github'
          tag: latest,${CIRCLE_TAG}
          context: orb/aws-ecr
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              only: master
